<?php

/**
 * @file
 * Contains alibraries.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function alibraries_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the alibraries module.
    case 'help.page.alibraries':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Libraries (Assets)') . '</p>';
      return $output;

    default:
  }
}
