<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_form_alter().
 *
 * Passes the parent entity language to the selection handler.
 *
 * @inheritdoc
 */
function language_access_fields_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  /** @var \Drupal\Core\Field\FieldItemListInterface $items */
  $items = $context['items'];
  /** @var \Drupal\Core\Field\FieldConfigInterface $field */
  $field = $items->getFieldDefinition();
  if ($field->getType() !== 'entity_reference') {
    return;
  }
  $handler = $field->getSetting('handler');
  if (strpos($handler, 'language_access_fields:') !== 0) {
    return;
  }
  $element['target_id']['#selection_settings']['parent_language'] = $items->getLangcode();
}
